version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          allow:
            - $gostd
            - github.com/luigimorel/gogen
            - github.com/urfave/cli/v2
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gosec
    - unconvert
    - dupl
    - misspell
    - gocritic
    - gocyclo
    - whitespace
    - bodyclose
    - depguard
    - dogsled

  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - nestif
