version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - unconvert
    - whitespace
  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - nestif
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/luigimorel/gogen
            - github.com/urfave/cli/v2
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/luigimorel/gogen
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
