version: 2
project_name: gogen
builds:
  - main: ./main.go
    binary: gogen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: luigimorel
    name: gogen
changelog:
  use: git
